version: '3.8'

services:
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    restart: always
    user: '0'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '3005:3005'
    volumes:
      - './grafana_data:/var/lib/grafana'
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3005/
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}
      GF_INSTALL_PLUGINS: ${GF_INSTALL_PLUGINS}
      GF_INSTALL_IMAGE_RENDERER_PLUGIN: true
      GF_UNIFIED_ALERTING_CAPTURE: true
      GF_UPLOAD_EXTERNAL_IMAGE_STORAGE: false
      GF_SERVER_HTTP_PORT: 3005
  renderer:
    image: grafana/grafana-image-renderer:latest
    links:
      - grafana
    environment:
      - ENABLE_METRICS=true
      - RENDERING_MODE=clustered # для возможности одновременной обработки большого количества изображений
      - RENDERING_CLUSTERING_MODE=context
      - RENDERING_CLUSTERING_MAX_CONCURRENCY=6
    ports:
      - 8081
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    user: '0'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8088:8088"
      - "8086:8086"
    volumes:
      - './influxdb.conf:/etc/influxdb/influxdb.conf:ro'
      - './influxdb_data:/var/lib/influxdb'
    # environment:
    #   - INFLUXDB_REPORTING_DISABLED=true
    #   - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
    #   - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
    #   - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    #   - INFLUXDB_AUTH_ENABLED=true
