version: '3.8'

services:
  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana
    restart: always
    user: '0'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '3005:3005'
    volumes:
      - './grafana_data:/var/lib/grafana'
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - GF_INSTALL_IMAGE_RENDERER_PLUGIN=true
      - GF_SERVER_HTTP_PORT=3005
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    user: '0'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - './influxdb.conf:/etc/influxdb/config.conf'
      - './influxdb_data:/var/lib/influxdb'
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_AUTH_ENABLED=true
